name: Vue Chatroom Deployment

on:
  push:
    branches: [release]  

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Windows, X64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: 'vue_chatroom_service'

    - name: Create .env.production
      working-directory: ./vue_chatroom_service
      run: |
        $envContent = "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}"
        [System.IO.File]::WriteAllText("$pwd\.env.production", $envContent)
        
        Get-Content .env.production

    - name: Build Docker Image
      working-directory: ./vue_chatroom_service
      run: |
        docker build -t vue-chatroom:latest .

    - name: Deploy Services
      working-directory: ./vue_chatroom_service
      run: |
        docker-compose down
        docker-compose up -d

    - name: Remove Old Images  
      run: |
          docker images --filter=reference='vue-chatroom:*' --format "{{.Repository}}:{{.Tag}}" | 
          Where-Object { $_ -ne "vue-chatroom:latest" } | 
          ForEach-Object { docker rmi -f $_ }
        
    - name: Cleanup Docker  
      if: success()
      run: |
        docker system prune -f --filter "until=24h"
        docker volume prune -f
